filetype off

set ruler laststatus=3 number title hlsearch
syntax on

" verkuerzt die Breite von <Tab> auf 4
set tabstop=4

" dient dazu unsichtbare zeichen sichtbar zu machen
set listchars=tab:▸\ ,
set list
hi SpecialKey ctermfg=7

" unmap arrow keys
no <down> <Nop>
no <left> <Nop>
no <right> <Nop>
no <up> <Nop>

ino <down> <Nop>
ino <left> <Nop>
ino <right> <Nop>
ino <up> <Nop>

colorscheme molokai

" lagert die swap-dateien aus
set directory=~/.vim/swap//,.

" toggles NERDTree with Ctrl+N
map <C-n> :NERDTreeToggle<CR>

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" plugin on GitHub repo
Plugin 'kroovysteph/snipmate.vim'
Plugin 'scrooloose/nerdtree'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
